[project]
name = "test-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
]
